name: flutter_template
description: "A new Flutter Blueprint Template attempts to provides some best practices, while avoiding weighing in on business logic."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.2

dependencies:
  cupertino_icons: ^1.0.8
  desktop_window: ^0.4.1
  dio: ^5.7.0
  dio_smart_retry: ^6.0.0
  equatable: ^2.0.5
  extra_alignments: ^1.0.0+1
  flextras: ^1.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_displaymode: ^0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.2
  flutter_secure_storage: ^9.2.2
  fresh_dio: ^0.4.2
  http_client_manager:
    path: ./packages/http_client_manager
  gap: ^3.0.1
  get_it: ^7.7.0
  get_it_mixin: ^4.2.2
  go_router: ^14.3.0
  image_fade: ^0.6.2
  intl: ^0.19.0
  logging: ^1.3.0
  pointer_interceptor: ^0.10.1+2
  shared_preferences: ^2.3.2
  sized_context: ^1.0.0+4
  very_good_analysis: ^6.0.0
  webview_flutter: ^4.9.0
  youtube_player_iframe: ^5.2.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/images/intro/